### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by CoryPlayzYT** [proxyplu/Nullify#43]
Hello, My School Blockes The Console And Bookmark Hacks Do You Know How To Get Around That? If Not Do You Know How To Do It On Something Like An Ipad?
[Screen recording 2023-02-21 8.30.05 AM.webm](https://user-images.githubusercontent.com/124921345/220373256-3601a8f7-f257-4b85-8f50-b627ac40a582.webm)

**Comment by TonicGaro** [comment]
Unfortunately with how I programmed the menu it's not possible to have full functionality with GitHub being blocked. You could try running the hacks individually by going into the Data folder and copying the scripts, then running them in the console, but expect things to be broken.
