### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kozio12** [proxyplu/Nullify#50]
how do i download this

**Comment by TonicGaro** [comment]
There is nothing you need to download. Simply copy the code below and paste it into the console (Ctrl + Shift + J) or run the code via a bookmark for easy access.

```js
javascript:fetch('https://raw.githubusercontent.com/proxyplu/Nullify/main/Data/main.js').then(r => r.text()).then(r => eval(r))
```

**Comment by CrazyCruzer182** [comment]
how can you do this on a chromebook?
